# Generated by Django 5.2.1 on 2025-05-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Подсказка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='подсказка', to='practice_test.question')),
            ],
        ),
    ]
