# Generated by Django 5.2.1 on 2025-05-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_test', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('selected_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_answered', 'Не отвечено'), ('correct', 'Правильно'), ('incorrect', 'Неправильно'), ('skipped', 'Пропущено')], default='not_answered', max_length=15)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_test.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_test.practicetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('test', 'question')},
            },
        ),
    ]
